project:
  type: website

website:
  repo-url: https://github.com/guibouland/ProjetGroupe
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "pollutionOcc"
  navbar:
    search: true
    tools: 
      - icon: github
        href: https://github.com/guibouland/ProjetGroupe
        text: GitHub
    left:
      - href: index.qmd
        text: Accueil
      - text: "Départements"
        menu:
          - Departements/Ariege.qmd
          - Departements/Aude.qmd
          - Departements/Aveyron.qmd
          - Departements/Gard.qmd
          - Departements/Gers.qmd
          - Departements/Haute-Garonne.qmd
          - Departements/Hautes-Pyrenees.qmd
          - Departements/Herault.qmd
          - Departements/Lot.qmd
          - Departements/Lozere.qmd
          - Departements/Pyrenees-Orientales.qmd
          - Departements/Tarn-et-Garonne.qmd
          - Departements/Tarn.qmd
      - href: about.qmd
        text: À propos
      - Avancee.qmd



format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, custom.css]
    code-fold: true
jupyter: python3

editor: visual

